#!/bin/bash
#
# DataQ Frontend Setup Script
# This script configures and deploys the DataQ Analyzer Frontend
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║           DataQ Analyzer Frontend Setup                   ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed.${NC}"
    echo "Please install Docker first: https://docs.docker.com/get-docker/"
    exit 1
fi

# Check for Docker Compose
if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed.${NC}"
    echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}✓ Docker and Docker Compose found${NC}"
echo ""

# Default values
DEFAULT_FRONTEND_PORT="8303"
DEFAULT_BACKEND_URL="http://host.docker.internal:3303"

# Get configuration from user
echo -e "${YELLOW}Configuration${NC}"
echo "─────────────────────────────────────────────────────────────"

# Frontend port
read -p "Frontend port [${DEFAULT_FRONTEND_PORT}]: " FRONTEND_PORT
FRONTEND_PORT="${FRONTEND_PORT:-$DEFAULT_FRONTEND_PORT}"

# Backend URL
echo ""
echo "Enter the backend URL. Examples:"
echo "  - http://host.docker.internal:3303  (backend on same host)"
echo "  - http://192.168.1.100:3303         (backend on another server)"
echo "  - http://backend.example.com:3303   (backend with hostname)"
echo ""
read -p "Backend URL [${DEFAULT_BACKEND_URL}]: " BACKEND_URL
BACKEND_URL="${BACKEND_URL:-$DEFAULT_BACKEND_URL}"

echo ""
echo -e "${YELLOW}Summary${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  Frontend Port:  ${FRONTEND_PORT}"
echo "  Backend URL:    ${BACKEND_URL}"
echo "  Frontend URL:   http://localhost:${FRONTEND_PORT}"
echo "─────────────────────────────────────────────────────────────"
echo ""

read -p "Proceed with these settings? [Y/n]: " CONFIRM
CONFIRM="${CONFIRM:-Y}"

if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}Setup cancelled.${NC}"
    exit 0
fi

# Create .env file
echo -e "${BLUE}Creating configuration...${NC}"
cat > .env << EOF
# DataQ Frontend Configuration
# Generated by setup.sh on $(date)

FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_URL=${BACKEND_URL}
EOF

echo -e "${GREEN}✓ Created .env file${NC}"

# Pull latest image
echo ""
echo -e "${BLUE}Pulling latest DataQ Frontend image...${NC}"
docker pull pandosme/dataq-frontend:latest
echo -e "${GREEN}✓ Image pulled successfully${NC}"

# Start the service
echo ""
echo -e "${BLUE}Starting DataQ Frontend...${NC}"
docker compose up -d

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Setup Complete!                                 ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "DataQ Frontend is now running at:"
echo -e "  ${BLUE}http://localhost:${FRONTEND_PORT}${NC}"
echo ""
echo "Useful commands:"
echo "  docker compose logs -f    # View logs"
echo "  docker compose down       # Stop the service"
echo "  docker compose up -d      # Start the service"
echo "  docker compose pull       # Update to latest version"
echo ""
